download models fix

diff --git a/backend/chat/Dockerfile b/backend/chat/Dockerfile
--- a/backend/chat/Dockerfile
+++ b/backend/chat/Dockerfile
@@ -1,4 +1,4 @@
-ARG BASE_IMAGE=ubuntu:latest
+ARG BASE_IMAGE=nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04
 
 FROM $BASE_IMAGE AS python-base
 ARG PROJECT_PATH
@@ -39,7 +39,7 @@ RUN --mount=from=ghcr.io/astral-sh/uv:latest,source=/uv,target=/bin/uv \
     --mount=type=secret,id=HF_TOKEN,env=HF_TOKEN,required=true \
         uv venv --python 3.12 --clear && \
         uv pip install huggingface-hub && \
-        uv run python - <<EOF
+        HF_HOME=/home/root/.cache/huggingface uv run python - <<EOF
 from huggingface_hub import snapshot_download
 import os
 
@@ -76,7 +76,7 @@ RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
     --mount=type=cache,target=/var/lib/apt,sharing=locked \
     apt update \
     && apt install -y --no-install-recommends \
-        build-essential
+        gh build-essential
 
 USER ${NONROOT_USERNAME}
 WORKDIR ${PROJECT_PATH}
@@ -87,10 +87,8 @@ WORKDIR ${PROJECT_PATH}
 # RUN gh auth setup-git
 
 # install runtime deps - without project itself
-    # uv download cache
-RUN --mount=type=cache,dst=${UV_CACHE_DIR},uid=1000,gid=1000 \
     # uv itself
-    --mount=from=ghcr.io/astral-sh/uv:latest,source=/uv,target=/bin/uv \
+RUN --mount=from=ghcr.io/astral-sh/uv:latest,source=/uv,target=/bin/uv \
     # Project files
     --mount=type=bind,source=pyproject.toml,target=${PROJECT_PATH}/pyproject.toml \
     --mount=type=bind,source=uv.lock,target=${PROJECT_PATH}/uv.lock \
@@ -112,6 +110,17 @@ RUN --mount=type=cache,dst=${UV_CACHE_DIR},uid=1000,gid=1000 \
 # for compatibility with prod stage COPY when uv is using python from /usr/bin
 RUN mkdir -p /home/${NONROOT_USERNAME}/.local/share/uv/python
 
+RUN --mount=type=secret,id=GIT_AUTH_TOKEN,env=GIT_AUTH_TOKEN,required=true \
+    if [ -z "${GIT_AUTH_TOKEN:-}" ]; then \
+        printf "\033[31mError: GIT_AUTH_TOKEN is missing or empty\033[0m\n" >&2; \
+        exit 1; \
+    fi && \
+    mkdir -p $HOME/models && \
+    GH_TOKEN="$GIT_AUTH_TOKEN" gh release download v1.0.0 \
+        --repo "Surveillance2024/SFTLLM" \
+        --pattern "llama3.1_8b_butler_lora.tar.gz" && \
+    tar -xzf llama3.1_8b_butler_lora.tar.gz -C "$HOME/models" && \
+    rm -f llama3.1_8b_butler_lora.tar.gz
 
 ################################################################################
 
@@ -150,6 +159,7 @@ COPY --chown=${NONROOT_USERNAME}:${NONROOT_USERNAME} --from=prod-prepare /home/$
 COPY --chown=${NONROOT_USERNAME}:${NONROOT_USERNAME} --from=prod-prepare ${VENV_PATH} ${VENV_PATH}
 
 COPY --exclude=.devcontainer/ --chown=${NONROOT_USERNAME}:${NONROOT_USERNAME} . .
+COPY --chown=${NONROOT_USERNAME}:${NONROOT_USERNAME} --from=prod-prepare /home/${NONROOT_USERNAME}/models/ ${PROJECT_PATH}/src/llm_pipeline/
 
 # RUN useradd -ms /bin/bash ${NONROOT_USERNAME} --user-group
 USER ${NONROOT_USERNAME}
